version: "3.8"

services:
  app:
    build:
      context: .
      target: build
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - tjms-network
    links:
      - db

  db:
    image: postgres:11.4
    env_file: ./dev/db_env_file
    networks:
      - tjms-network
    ports:
      - "5432:5432"
    expose:
      - "5432"

networks:
  tjms-network:
    name: tjms-network
    driver: "bridge"
