version: "3.8"

services:
  app:
    build:
      context: .
      target: app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - tjms-network
    depends_on:
      - db

  db:
    image: postgres:11.4
    networks:
      - tjms-network
    ports:
      - "5434:5434"
    expose:
      - "5434"

networks:
  tjms-network:
    name: tjms-network
    driver: "bridge"
