version: "3.8"

services:
  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    networks:
      - tjms
    ports:
      - "8761:8761"

  nomeacao:
    build:
      context: ./nomeacao
      dockerfile: Dockerfile
    networks:
      - tjms
    environment:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka
    ports:
      - "8081:8081"

  cadastro:
    build:
      context: ./cadastro
      dockerfile: Dockerfile
    networks:
      - tjms
    environment:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka
    ports:
      - "8080:8080"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    networks:
      - tjms
    environment:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka
    ports:
      - "9191:9191"
    depends_on:
      - service-registry
      - nomeacao
      - cadastro

networks:
  tjms:
    name: tjms
    driver: "bridge"
