version: "3.8"

services:
  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    networks:
      - tjms
    ports:
      - "8761:8761"

  nomeacao:
    build:
      context: ./nomeacao
      dockerfile: Dockerfile
    networks:
      - tjms
    environment:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka
    ports:
      - "8081:8081"

  cadastro:
    build:
      context: ./cadastro
      dockerfile: Dockerfile
    networks:
      - tjms
    environment:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka
      - KAFKA_SERVER_URL= kafka:29092
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    networks:
      - tjms
    environment:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka
    ports:
      - "9191:9191"
    depends_on:
      - service-registry
      - nomeacao
      - cadastro

  kafka:
    image: landoop/fast-data-dev:latest
    container_name: kafka
    networks:
      - tjms
    ports:
      - 3181:3181
      - 3040:3040
      - 7082:7082
      - 7083:7083
      - 9092:9092
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
      SAMPLEDATA: 0
      BROKER_PORT: 9092
      REST_PORT: 7082
      CONNECT_PORT: 7083
      ZK_PORT: 3181
      WEB_PORT: 3040
      REGISTRY_PORT: 8081
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - tjms
    ports:
      - "2181:2181"

networks:
  tjms:
    name: tjms
    driver: "bridge"
